name: RankShop
author: PiloudeDakar
version: 1.0
api-version: 4.0.0
main: PiloudeDakar/RankShop/Main
softdepend:
  - EconomyAPI
  - PurePerms

commands:
  up:
    description: open the rank shop
    usage: up