name: RankShop
author: PiloudeDakar
version: 1.0
api: 4.0.0
main: PiloudeDakar\RankShop\Main
depend:
  - EconomyAPI
  - PurePerms

commands:
  up:
    description: open the rank shop
    usage: up
    permission: RankShop.up
    
permissions:
  RankShop.up:
    default: op
