#title of the main form
title: RankShop by PiloudeDakar

#content of the main form
content: Choose a rank to buy

#exampleRank:
#  title: Example rank
#  content: Buy the example rank
#  name: [the perfect name of the rank, with colors] ยง3Example rank
#  price: 100000